@baseUrl = http://localhost:3000
@userId = 6a44fcb0dc3e1cf8f09a351a
@tripId = 6a60aea2a22c59f2079c8437
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTU0Y2MxNmJkOTY2ZDYwY2VhMDcwYTEiLCJpYXQiOjE3ODQ4MDYxMDcsImV4cCI6MTc4NDg5MjUwN30.VFdbbdtGTwOnqwJ7w9eJS0QXKtycNjKvk6tQpYVr1tI

### TEST API
GET {{baseUrl}}

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe6@example.com",
  "password": "test123"
}

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{userId}}

### UPDATE USER BY ID
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated"
}

### DELETE USER BY ID
DELETE {{baseUrl}}/users/{{userId}}

### REGISTER USER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe2@example.com",
  "password": "test123"
}

### LOGIN USER
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "jane@example.com",
  "password": "test123"
}

### CREATE TRIP
POST {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trip to the moon",
  "startDate": "2025-12-15",
  "endDate": "2025-12-16",
  "budget": {
    "total": 1000
  },
  "destinations": ["Moon", "Mars", "Jupiter"]
}

### GET ALL TRIPS
GET {{baseUrl}}/trips
Authorization: Bearer {{token}}

### GET TRIP BY ID
GET {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}

### UPDATE TRIP BY ID
PATCH {{baseUrl}}/trips/{{tripId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trip to the moon and back",
  "budget": {
    "total": 1500
  }
}

### DELETE TRIP BY ID
DELETE {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}
