@baseUrl = http://localhost:3000
@userId = 6a44fcb0dc3e1cf8f09a351a

### TEST API
GET {{baseUrl}}

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe6@example.com",
  "password": "test123"
}

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{userId}}

### UPDATE USER BY ID
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated"
}

### DELETE USER BY ID
DELETE {{baseUrl}}/users/{{userId}}

### REGISTER USER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe2@example.com",
  "password": "test123"
}

### LOGIN USER
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "jane@example.com",
  "password": "test123"
}

### CREATE TRIP
POST {{baseUrl}}/trips
Content-Type: application/json

{
  "user": "{{userId}}",
  "title": "Trip to the moon",
  "startDate": "2025-12-15",
  "endDate": "2025-12-16",
  "budget": {
    "total": 1000
  },
  "destinations": ["Moon", "Mars", "Jupiter"]
}
